using System.Text.Json.Serialization;

namespace DevOpsCodeReviewer.Functions.Models;

/// <summary>
/// LLM response containing code review comments.
/// </summary>
public class CodeReviewResponse
{
    /// <summary>
    /// Array of review comments generated by the LLM.
    /// </summary>
    [JsonPropertyName("comments")]
    public List<ReviewComment> Comments { get; set; } = [];

    /// <summary>
    /// Overall summary of the code review.
    /// </summary>
    [JsonPropertyName("summary")]
    public string? Summary { get; set; }

    /// <summary>
    /// Number of files reviewed.
    /// </summary>
    [JsonPropertyName("filesReviewed")]
    public int FilesReviewed { get; set; }

    /// <summary>
    /// Number of lines reviewed.
    /// </summary>
    [JsonPropertyName("linesReviewed")]
    public int LinesReviewed { get; set; }

    /// <summary>
    /// Token usage for this request.
    /// </summary>
    [JsonPropertyName("tokenUsage")]
    public TokenUsage? TokenUsage { get; set; }
}

/// <summary>
/// Token usage statistics from the LLM call.
/// </summary>
public class TokenUsage
{
    [JsonPropertyName("promptTokens")]
    public int PromptTokens { get; set; }

    [JsonPropertyName("completionTokens")]
    public int CompletionTokens { get; set; }

    [JsonPropertyName("totalTokens")]
    public int TotalTokens { get; set; }
}
