using DevOpsCodeReviewer.Core.Models;

namespace DevOpsCodeReviewer.Core.Agents;

/// <summary>
/// Input for the Overview Agent.
/// </summary>
public class OverviewInput
{
    /// <summary>
    /// The diff analysis from the Diff Analyzer Agent.
    /// </summary>
    public DiffAnalysis Analysis { get; set; } = new();

    /// <summary>
    /// The code review comments generated by the Code Review Agent.
    /// </summary>
    public List<ReviewComment> Comments { get; set; } = [];

    /// <summary>
    /// The original code review request.
    /// </summary>
    public CodeReviewRequest Request { get; set; } = new();

    /// <summary>
    /// Execution context with PR metadata.
    /// </summary>
    public AgentExecutionContext ExecutionContext { get; set; } = new();
}

/// <summary>
/// Agent responsible for generating the high-level overview and validating scores.
/// </summary>
/// <remarks>
/// This agent runs AFTER the Code Review Agent and:
/// - Synthesizes comments into a high-level summary
/// - Generates risk assessment based on actual findings
/// - Validates and clamps scores to 1-5 range
/// - Identifies key changes and important files
/// - Can flag inconsistencies in comment severities
/// </remarks>
public interface IOverviewAgent : IAgent<OverviewInput, ReviewOverview>
{
}
